// front-admin/src/layouts/styles.js
export const styles = {
  appContainer: {
    display: "flex",
    minHeight: "100vh",
    backgroundColor: "#f5f7fa",
  },
  sidebar: {
    width: "280px",
    backgroundColor: "white",
    boxShadow: "0 0 20px rgba(0, 0, 0, 0.05)",
    padding: "24px 0",
    position: "sticky",
    top: 0,
    height: "100vh",
    justifyContent: "space-between",
    flexDirection: "column",
    display: "flex",
    overflowY: "auto",
    scrollBehavior: "smooth",
    borderRight: "1px solid #e5e7eb",
  },
  logo: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    padding: "0 24px 24px",
    marginBottom: "16px",
    borderBottom: "1px solid #e5e7eb",
    position: "sticky",
    top: -24,
    backgroundColor: "white",
    zIndex: 10,
  },
  logoIcon: {
    width: "36px",
    height: "36px",
    borderRadius: "10px",
    background: "linear-gradient(135deg, #3b82f6, #8b5cf6)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "white",
    boxShadow: "0 4px 12px rgba(59, 130, 246, 0.3)",
  },
  logoText: {
    fontSize: "20px",
    fontWeight: "bold",
    color: "#111827",
    letterSpacing: "-0.5px",
  },
  nav: {
    display: "flex",
    flexDirection: "column",
    gap: "2px",
    padding: "0 16px",
    flex: 1,
  },
  navLink: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    padding: "12px 16px",
    borderRadius: "8px",
    textDecoration: "none",
    color: "#6b7280",
    fontWeight: "500",
    fontSize: "14px",
    transition: "all 0.2s ease",
    margin: "1px 0",
    border: "none",
    cursor: "pointer",
    position: "relative",
  },
  navLinkActive: {
    backgroundColor: "#eff6ff",
    color: "#3b82f6",
    borderLeft: "3px solid #3b82f6",
    fontWeight: "600",
  },
  navLinkHover: {
    backgroundColor: "#f9fafb",
    color: "#374151",
  },
  navLinkIcon: {
    width: "18px",
    height: "18px",
    flexShrink: 0,
  },
  mainContent: {
    flex: 1,
    padding: "0",
    backgroundColor: "#f8fafc",
    minHeight: "100vh",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "32px",
    padding: "24px 32px 0",
    backgroundColor: "white",
    borderBottom: "1px solid #e5e7eb",
    position: "sticky",
    top: 0,
    zIndex: 5,
  },
  pageTitle: {
    fontSize: "28px",
    fontWeight: "bold",
    color: "#111827",
    margin: 0,
  },
  contentCard: {
    backgroundColor: "white",
    borderRadius: "12px",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.1)",
    padding: "24px",
    margin: "24px",
  },
  userSection: {
    marginTop: "auto",
    padding: "20px 16px 16px",
    borderTop: "1px solid #e5e7eb",
    position: "sticky",
    bottom: 0,
    backgroundColor: "white",
    zIndex: 10,
  },
  userInfo: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    marginBottom: "12px",
    padding: "8px",
    borderRadius: "8px",
    transition: "background-color 0.2s ease",
  },
  userInfoHover: {
    backgroundColor: "#f9fafb",
  },
  avatar: {
    width: "40px",
    height: "40px",
    borderRadius: "50%",
    backgroundColor: "#e5e7eb",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "16px",
    fontWeight: "600",
    color: "#6b7280",
    border: "2px solid #f3f4f6",
  },
  userName: {
    fontSize: "14px",
    fontWeight: "600",
    color: "#111827",
    margin: 0,
  },
  userRole: {
    fontSize: "12px",
    color: "#6b7280",
    margin: 0,
  },
  userActions: {
    display: "flex",
    gap: "8px",
  },
  userButton: {
    padding: "6px 12px",
    border: "1px solid #e5e7eb",
    borderRadius: "6px",
    backgroundColor: "white",
    color: "#6b7280",
    fontSize: "12px",
    fontWeight: "500",
    cursor: "pointer",
    transition: "all 0.2s ease",
    textDecoration: "none",
    display: "inline-flex",
    alignItems: "center",
    gap: "4px",
  },
  userButtonHover: {
    backgroundColor: "#f9fafb",
    borderColor: "#d1d5db",
    color: "#374151",
  },
  logoutButton: {
    backgroundColor: "#fef2f2",
    color: "#dc2626",
    borderColor: "#fecaca",
  },
  logoutButtonHover: {
    backgroundColor: "#fee2e2",
    borderColor: "#fca5a5",
  },
  // Styles pour les badges de rôle
  roleBadge: {
    padding: "8px 12px",
    borderRadius: "6px",
    fontSize: "12px",
    fontWeight: "600",
    textAlign: "center",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
    margin: "0 24px 16px",
  },
  roleBadgeAdmin: {
    backgroundColor: "#fef2f2",
    color: "#dc2626",
    border: "1px solid #fecaca",
  },
  roleBadgeManager: {
    backgroundColor: "#f0f9ff",
    color: "#0369a1",
    border: "1px solid #bae6fd",
  },
  roleBadgeReporter: {
    backgroundColor: "#f0fdf4",
    color: "#16a34a",
    border: "1px solid #bbf7d0",
  },
  roleBadgeUser: {
    backgroundColor: "#f9fafb",
    color: "#6b7280",
    border: "1px solid #e5e7eb",
  },
  // Styles pour les actions rapides
  quickActionsSection: {
    padding: "16px",
    marginTop: "20px",
    borderTop: "1px solid #e5e7eb",
  },
  quickActionsTitle: {
    fontSize: "12px",
    fontWeight: "600",
    color: "#6b7280",
    marginBottom: "12px",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
  },
  quickActionButton: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "8px 12px",
    backgroundColor: "#f0f9ff",
    color: "#0369a1",
    borderRadius: "8px",
    fontSize: "14px",
    fontWeight: "500",
    border: "1px solid #e0f2fe",
    textDecoration: "none",
    transition: "all 0.2s ease",
    cursor: "pointer",
  },
  quickActionButtonHover: {
    backgroundColor: "#e0f2fe",
    borderColor: "#bae6fd",
    transform: "translateY(-1px)",
  },

  userSection: {
    marginTop: "auto",
    padding: "16px",
    borderTop: "1px solid #e5e7eb",
    marginBottom: "20px",
    position: "sticky",
    bottom: 0,
    backgroundColor: "white",
    zIndex: 10,
  },
  userInfo: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    marginBottom: "16px",
  },
  avatar: {
    width: "40px",
    height: "40px",
    borderRadius: "50%",
    backgroundColor: "#3b82f6",
    color: "white",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  userDetails: {
    flex: 1,
    overflow: "hidden",
  },
  username: {
    fontWeight: "600",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  role: {
    fontSize: "12px",
    color: "#6b7280",
  },
  userMenu: {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
  },
  userMenuItem: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "8px 12px",
    borderRadius: "6px",
    color: "#4b5563",
    textDecoration: "none",
    fontSize: "14px",
  },
  logoutMenuItem: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "8px 12px",
    borderRadius: "6px",
    color: "#ef4444",
    textDecoration: "none",
    fontSize: "14px",
  },
  loginButton: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "10px 16px",
    borderRadius: "8px",
    backgroundColor: "#3b82f6",
    color: "white",
    border: "none",
    cursor: "pointer",
    fontWeight: "500",
  },
};
