export const styles = {
  appContainer: {
    display: "flex",
    minHeight: "100vh",
    backgroundColor: "#f5f7fa",
  },
  sidebar: {
    width: "240px",
    backgroundColor: "white",
    boxShadow: "0 0 20px rgba(0, 0, 0, 0.05)",
    padding: "24px 0",
    position: "sticky",
    top: 0,
    height: "100vh",
    justifyContent: "space-between",
    flexDirection: "column",
    display: "flex",
  },
  logo: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    padding: "0 24px 24px",
    marginBottom: "16px",
    borderBottom: "1px solid #e5e7eb",
  },
  logoIcon: {
    width: "32px",
    height: "32px",
    borderRadius: "8px",
    background: "linear-gradient(135deg, #3b82f6, #8b5cf6)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "white",
  },
  logoText: {
    fontSize: "18px",
    fontWeight: "bold",
    color: "#111827",
  },
  nav: {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
    padding: "0 16px",
  },
  navLink: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    padding: "12px 16px",
    borderRadius: "8px",
    textDecoration: "none",
    color: "#6b7280",
    fontWeight: "500",
    transition: "all 0.2s ease",
  },
  navLinkActive: {
    backgroundColor: "#f0f5ff",
    color: "#3b82f6",
  },
  navLinkHover: {
    backgroundColor: "#f9fafb",
  },
  navLinkIcon: {
    width: "20px",
    height: "20px",
  },
  mainContent: {
    flex: 1,
    padding: "32px",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "32px",
  },
  pageTitle: {
    fontSize: "24px",
    fontWeight: "bold",
    color: "#111827",
  },
  contentCard: {
    backgroundColor: "white",
    borderRadius: "12px",
    // boxShadow: "0 4px 12px rgba(0, 0, 0, 0.05)",
    padding: "24px",
  },
  userSection: {
    marginTop: "auto",
    padding: "16px",
    borderTop: "1px solid #e5e7eb",
    marginBottom: "16px",
  },
  userInfo: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    marginBottom: "16px",
  },
  avatar: {
    width: "40px",
    height: "40px",
    borderRadius: "50%",
    backgroundColor: "#3b82f6",
    color: "white",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  userDetails: {
    flex: 1,
    overflow: "hidden",
  },
  username: {
    fontWeight: "600",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  role: {
    fontSize: "12px",
    color: "#6b7280",
  },
  userMenu: {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
  },
  userMenuItem: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "8px 12px",
    borderRadius: "6px",
    color: "#4b5563",
    textDecoration: "none",
    fontSize: "14px",
  },
  logoutMenuItem: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "8px 12px",
    borderRadius: "6px",
    color: "#ef4444",
    textDecoration: "none",
    fontSize: "14px",
  },
  loginButton: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "10px 16px",
    borderRadius: "8px",
    backgroundColor: "#3b82f6",
    color: "white",
    border: "none",
    cursor: "pointer",
    fontWeight: "500",
  },
};
