export const styles = {
  container: {
    padding: "24px",
    maxWidth: "1400px",
    margin: "0 auto",
  },
  loadingContainer: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    height: "400px",
    fontSize: "16px",
    color: "#6b7280",
    gap: "16px",
  },
  errorContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "60px 20px",
    color: "#dc2626",
  },
  retryButton: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    backgroundColor: "#3b82f6",
    color: "white",
    border: "none",
    padding: "12px 24px",
    borderRadius: "8px",
    cursor: "pointer",
    marginTop: "16px",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "32px",
  },
  teamHeader: {
    display: "flex",
    alignItems: "center",
    gap: "16px",
  },
  teamLogo: {
    width: "60px",
    height: "60px",
    borderRadius: "8px",
    objectFit: "cover",
    border: "2px solid #e5e7eb",
  },
  teamLogoSmall: {
    width: "32px",
    height: "32px",
    borderRadius: "4px",
    objectFit: "cover",
    border: "1px solid #e5e7eb",
  },
  title: {
    fontSize: "28px",
    fontWeight: "bold",
    color: "#111827",
    marginBottom: "8px",
  },
  subtitle: {
    fontSize: "16px",
    color: "#6b7280",
  },
  refreshButton: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    backgroundColor: "#f3f4f6",
    color: "#374151",
    border: "1px solid #d1d5db",
    padding: "8px 16px",
    borderRadius: "6px",
    cursor: "pointer",
  },
  liveAlert: {
    backgroundColor: "#dcfce7",
    border: "2px solid #16a34a",
    borderRadius: "12px",
    padding: "20px",
    marginBottom: "24px",
  },
  liveIndicator: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    color: "#16a34a",
    fontSize: "14px",
    fontWeight: "bold",
    marginBottom: "8px",
  },
  liveDot: {
    width: "8px",
    height: "8px",
    backgroundColor: "#16a34a",
    borderRadius: "50%",
    animation: "pulse 2s infinite",
  },
  liveMatchInfo: {
    display: "flex",
    justifyContent: "space-between",
    fontSize: "16px",
    fontWeight: "600",
    color: "#16a34a",
  },
  metricsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))",
    gap: "20px",
    marginBottom: "32px",
  },
  metricCard: {
    display: "flex",
    alignItems: "center",
    backgroundColor: "white",
    padding: "24px",
    borderRadius: "12px",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.1)",
    border: "1px solid #f3f4f6",
  },
  metricIcon: {
    backgroundColor: "#eff6ff",
    color: "#3b82f6",
    padding: "12px",
    borderRadius: "10px",
    marginRight: "16px",
  },
  metricContent: {
    flex: 1,
  },
  metricValue: {
    fontSize: "24px",
    fontWeight: "bold",
    color: "#111827",
  },
  metricLabel: {
    fontSize: "14px",
    color: "#6b7280",
    marginBottom: "4px",
  },
  metricSubtext: {
    fontSize: "12px",
    color: "#9ca3af",
  },
  dashboardGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(400px, 1fr))",
    gap: "24px",
  },
  section: {
    backgroundColor: "white",
    padding: "24px",
    borderRadius: "12px",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.1)",
    border: "1px solid #f3f4f6",
  },
  sectionHeader: {
    marginBottom: "20px",
  },
  sectionTitle: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontSize: "18px",
    fontWeight: "bold",
    color: "#111827",
  },
  // Manager Dashboard styles
  matchesList: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  matchItem: {
    display: "grid",
    gridTemplateColumns: "80px 1fr 80px 60px",
    gap: "12px",
    alignItems: "center",
    padding: "12px",
    backgroundColor: "#f9fafb",
    borderRadius: "8px",
    border: "1px solid #e5e7eb",
  },
  matchDate: {
    fontSize: "12px",
    color: "#6b7280",
  },
  matchTeams: {
    fontSize: "14px",
    fontWeight: "500",
  },
  matchScore: {
    fontSize: "16px",
    fontWeight: "bold",
    textAlign: "center",
  },
  matchResult: {
    padding: "4px 8px",
    borderRadius: "4px",
    fontSize: "12px",
    fontWeight: "bold",
    textAlign: "center",
  },
  upcomingList: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  upcomingMatch: {
    display: "grid",
    gridTemplateColumns: "100px 1fr 120px",
    gap: "12px",
    alignItems: "center",
    padding: "16px",
    backgroundColor: "#f9fafb",
    borderRadius: "8px",
    border: "1px solid #e5e7eb",
  },
  upcomingDate: {
    fontSize: "12px",
    color: "#6b7280",
  },
  upcomingTime: {
    fontSize: "11px",
    color: "#3b82f6",
    fontWeight: "500",
    marginTop: "2px",
  },
  upcomingOpponent: {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
  },
  opponentName: {
    fontSize: "14px",
    fontWeight: "600",
    color: "#111827",
  },
  upcomingVenue: {
    fontSize: "12px",
    color: "#6b7280",
    textAlign: "right",
  },
  playersList: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(240px, 1fr))",
    gap: "12px",
  },
  playerItem: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    padding: "12px",
    backgroundColor: "#f9fafb",
    borderRadius: "8px",
    border: "1px solid #e5e7eb",
  },
  playerNumber: {
    width: "32px",
    height: "32px",
    backgroundColor: "#3b82f6",
    color: "white",
    borderRadius: "6px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "14px",
    fontWeight: "bold",
  },
  playerInfo: {
    flex: 1,
  },
  playerName: {
    fontSize: "14px",
    fontWeight: "600",
    color: "#111827",
  },
  playerPosition: {
    fontSize: "12px",
    color: "#6b7280",
  },
  playerStats: {
    fontSize: "12px",
    color: "#059669",
    fontWeight: "500",
  },
  // Events Management styles
  matchSelector: {
    backgroundColor: "white",
    padding: "20px",
    borderRadius: "12px",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.1)",
    marginBottom: "24px",
  },
  selectorLabel: {
    display: "block",
    fontSize: "14px",
    fontWeight: "600",
    color: "#374151",
    marginBottom: "8px",
  },
  selector: {
    width: "100%",
    padding: "12px",
    border: "1px solid #d1d5db",
    borderRadius: "8px",
    fontSize: "16px",
    backgroundColor: "white",
  },
  matchInfo: {
    backgroundColor: "white",
    padding: "24px",
    borderRadius: "12px",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.1)",
    marginBottom: "24px",
  },
  matchHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  matchTeams: {
    display: "flex",
    alignItems: "center",
    gap: "24px",
    fontSize: "18px",
    fontWeight: "600",
  },
  teamSection: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    minWidth: "200px",
  },
  teamName: {
    fontSize: "16px",
    fontWeight: "600",
  },
  matchScore: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    backgroundColor: "#f3f4f6",
    padding: "16px 24px",
    borderRadius: "12px",
  },
  scoreNumber: {
    fontSize: "28px",
    fontWeight: "bold",
    color: "#111827",
    minWidth: "32px",
    textAlign: "center",
  },
  scoreSeparator: {
    fontSize: "24px",
    color: "#6b7280",
  },
  matchStatus: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-end",
    gap: "8px",
  },
  currentTime: {
    fontSize: "20px",
    fontWeight: "bold",
    color: "#16a34a",
  },
  matchStatusText: {
    fontSize: "14px",
    color: "#6b7280",
  },
  mainContent: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "24px",
  },
  eventForm: {
    backgroundColor: "white",
    padding: "24px",
    borderRadius: "12px",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.1)",
  },
  form: {
    display: "flex",
    flexDirection: "column",
    gap: "20px",
  },
  formRow: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "16px",
  },
  formGroup: {
    display: "flex",
    flexDirection: "column",
  },
  label: {
    fontSize: "14px",
    fontWeight: "600",
    color: "#374151",
    marginBottom: "6px",
  },
  input: {
    padding: "10px 12px",
    border: "1px solid #d1d5db",
    borderRadius: "6px",
    fontSize: "14px",
  },
  addButton: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    backgroundColor: "#16a34a",
    color: "white",
    border: "none",
    padding: "12px 24px",
    borderRadius: "8px",
    fontSize: "16px",
    fontWeight: "600",
    cursor: "pointer",
  },
  eventsList: {
    backgroundColor: "white",
    padding: "24px",
    borderRadius: "12px",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.1)",
  },
  eventsContainer: {
    maxHeight: "500px",
    overflowY: "auto",
  },
  eventItem: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    padding: "12px",
    borderBottom: "1px solid #f3f4f6",
    backgroundColor: "#fafafa",
    borderRadius: "8px",
    marginBottom: "8px",
  },
  eventTime: {
    fontSize: "14px",
    fontWeight: "bold",
    color: "#16a34a",
    minWidth: "40px",
    textAlign: "center",
    backgroundColor: "#dcfce7",
    padding: "4px 8px",
    borderRadius: "4px",
  },
  eventIcon: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    minWidth: "32px",
  },
  eventDetails: {
    flex: 1,
  },
  eventType: {
    fontWeight: "600",
    color: "#111827",
    fontSize: "14px",
  },
  eventPlayer: {
    color: "#6b7280",
    fontSize: "13px",
  },
  eventTeam: {
    color: "#3b82f6",
    fontSize: "12px",
    fontWeight: "500",
  },
  noEvents: {
    textAlign: "center",
    padding: "40px",
    color: "#6b7280",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  // Admin Dashboard styles
  leaderboard: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  leaderboardItem: {
    display: "flex",
    alignItems: "center",
    gap: "16px",
    padding: "16px 12px",
    backgroundColor: "#f9fafb",
    borderRadius: "8px",
    border: "1px solid #e5e7eb",
  },
  position: {
    fontSize: "16px",
    fontWeight: "bold",
    color: "#374151",
    minWidth: "30px",
  },
  teamInfo: {
    flex: 1,
  },
  teamStats: {
    fontSize: "12px",
    color: "#6b7280",
    marginTop: "2px",
  },
  teamPoints: {
    textAlign: "right",
  },
  points: {
    fontSize: "18px",
    fontWeight: "bold",
    color: "#059669",
  },
  goalDiff: {
    fontSize: "12px",
    color: "#6b7280",
  },
  activitiesList: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  activityItem: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    padding: "12px",
    backgroundColor: "#f9fafb",
    borderRadius: "8px",
    border: "1px solid #e5e7eb",
  },
  activityIcon: {
    backgroundColor: "#eff6ff",
    color: "#3b82f6",
    padding: "8px",
    borderRadius: "6px",
  },
  activityContent: {
    flex: 1,
  },
  activityMessage: {
    fontSize: "14px",
    color: "#111827",
  },
  activityTime: {
    fontSize: "12px",
    color: "#6b7280",
  },
  activityStatus: {},
  statusLive: {
    backgroundColor: "#dcfce7",
    color: "#16a34a",
    padding: "4px 8px",
    borderRadius: "4px",
    fontSize: "12px",
    fontWeight: "600",
  },
  statusCompleted: {
    backgroundColor: "#f3f4f6",
    color: "#6b7280",
    padding: "4px 8px",
    borderRadius: "4px",
    fontSize: "12px",
    fontWeight: "600",
  },
  statusNew: {
    backgroundColor: "#dbeafe",
    color: "#3b82f6",
    padding: "4px 8px",
    borderRadius: "4px",
    fontSize: "12px",
    fontWeight: "600",
  },
  noActivities: {
    textAlign: "center",
    padding: "20px",
    color: "#6b7280",
  },
  roleStats: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  roleItem: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  roleLabel: {
    minWidth: "80px",
    fontSize: "14px",
    fontWeight: "500",
  },
  roleCount: {
    minWidth: "30px",
    fontSize: "14px",
    fontWeight: "bold",
  },
  roleBar: {
    flex: 1,
    height: "8px",
    backgroundColor: "#f3f4f6",
    borderRadius: "4px",
    overflow: "hidden",
  },
  roleBarFill: {
    height: "100%",
    transition: "width 0.3s ease",
  },
  alertsList: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  alertItem: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "12px",
    backgroundColor: "#fffbeb",
    borderRadius: "6px",
    fontSize: "14px",
    color: "#92400e",
    border: "1px solid #fed7aa",
  },
  noAlerts: {
    textAlign: "center",
    padding: "20px",
    color: "#16a34a",
    backgroundColor: "#f0fdf4",
    borderRadius: "6px",
    border: "1px solid #bbf7d0",
  },
  emptyState: {
    textAlign: "center",
    padding: "40px 20px",
    color: "#6b7280",
  },
  emptyIcon: {
    marginBottom: "16px",
    color: "#9ca3af",
  },
};
