// ==================== STYLES ====================
export const styles = {
  container: {
    padding: "24px",
    maxWidth: "1200px",
    margin: "0 auto",
  },
  loadingContainer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: "400px",
    fontSize: "16px",
    color: "#6b7280",
  },
  header: {
    marginBottom: "32px",
  },
  title: {
    fontSize: "28px",
    fontWeight: "bold",
    color: "#111827",
    marginBottom: "8px",
  },
  subtitle: {
    fontSize: "16px",
    color: "#6b7280",
  },
  metricsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
    gap: "20px",
    marginBottom: "32px",
  },
  metricCard: {
    display: "flex",
    alignItems: "center",
    backgroundColor: "white",
    padding: "20px",
    borderRadius: "12px",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.1)",
  },
  metricIcon: {
    backgroundColor: "#eff6ff",
    color: "#3b82f6",
    padding: "12px",
    borderRadius: "10px",
    marginRight: "16px",
  },
  metricContent: {},
  metricValue: {
    fontSize: "24px",
    fontWeight: "bold",
    color: "#111827",
  },
  metricLabel: {
    fontSize: "14px",
    color: "#6b7280",
  },
  section: {
    marginBottom: "32px",
  },
  sectionTitle: {
    fontSize: "20px",
    fontWeight: "bold",
    marginBottom: "16px",
    color: "#111827",
  },
  liveMatchCard: {
    backgroundColor: "white",
    padding: "20px",
    borderRadius: "12px",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.1)",
    border: "2px solid #10b981",
  },
  liveIndicator: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    backgroundColor: "#dcfce7",
    color: "#16a34a",
    padding: "4px 8px",
    borderRadius: "6px",
    fontSize: "12px",
    fontWeight: "bold",
    width: "fit-content",
    marginBottom: "12px",
  },
  liveDot: {
    width: "8px",
    height: "8px",
    backgroundColor: "#16a34a",
    borderRadius: "50%",
    animation: "pulse 2s infinite",
  },
  matchInfo: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  teams: {
    display: "flex",
    alignItems: "center",
    gap: "16px",
  },
  score: {
    fontSize: "18px",
    fontWeight: "bold",
    backgroundColor: "#f3f4f6",
    padding: "4px 12px",
    borderRadius: "6px",
  },
  matchTime: {
    fontSize: "14px",
    fontWeight: "bold",
    color: "#059669",
  },
  actionButton: {
    backgroundColor: "#3b82f6",
    color: "white",
    border: "none",
    padding: "8px 16px",
    borderRadius: "6px",
    cursor: "pointer",
    fontSize: "14px",
  },
  matchesList: {
    display: "flex",
    flexDirection: "column",
    gap: "16px",
  },
  matchCard: {
    backgroundColor: "white",
    padding: "20px",
    borderRadius: "12px",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.1)",
  },
  matchHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "16px",
  },
  matchDate: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    fontSize: "14px",
    color: "#6b7280",
  },
  matchStatus: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  statusScheduled: {
    backgroundColor: "#e0f2fe",
    color: "#0369a1",
    padding: "4px 8px",
    borderRadius: "4px",
    fontSize: "12px",
    fontWeight: "600",
  },
  statusLive: {
    backgroundColor: "#dcfce7",
    color: "#16a34a",
    padding: "4px 8px",
    borderRadius: "4px",
    fontSize: "12px",
    fontWeight: "600",
  },
  statusCompleted: {
    backgroundColor: "#f3f4f6",
    color: "#6b7280",
    padding: "4px 8px",
    borderRadius: "4px",
    fontSize: "12px",
    fontWeight: "600",
  },
  matchContent: {
    marginBottom: "16px",
  },
  team: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    minWidth: "120px",
  },
  teamName: {
    fontWeight: "600",
    textAlign: "center",
  },
  homeIndicator: {
    fontSize: "12px",
    color: "#059669",
    backgroundColor: "#d1fae5",
    padding: "2px 6px",
    borderRadius: "4px",
    marginTop: "4px",
  },
  awayIndicator: {
    fontSize: "12px",
    color: "#dc2626",
    backgroundColor: "#fee2e2",
    padding: "2px 6px",
    borderRadius: "4px",
    marginTop: "4px",
  },
  vs: {
    fontSize: "14px",
    color: "#6b7280",
    fontWeight: "500",
  },
  emptyState: {
    textAlign: "center",
    padding: "60px 20px",
    color: "#6b7280",
  },
  emptyIcon: {
    marginBottom: "16px",
    color: "#9ca3af",
  },
  upcomingMatches: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  upcomingMatch: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "white",
    padding: "16px",
    borderRadius: "8px",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.1)",
  },
  upcomingDate: {
    fontSize: "14px",
    color: "#6b7280",
    fontWeight: "500",
  },
  upcomingTeams: {
    fontWeight: "600",
    color: "#111827",
  },
  upcomingTime: {
    fontSize: "14px",
    color: "#3b82f6",
    fontWeight: "500",
  },
  filters: {
    display: "flex",
    gap: "12px",
    marginBottom: "24px",
  },
  filterButton: {
    padding: "8px 16px",
    border: "1px solid #d1d5db",
    backgroundColor: "white",
    borderRadius: "6px",
    cursor: "pointer",
    fontSize: "14px",
  },
  activeFilter: {
    backgroundColor: "#3b82f6",
    color: "white",
    borderColor: "#3b82f6",
  },
  status: {
    padding: "4px 8px",
    borderRadius: "4px",
    fontSize: "12px",
    fontWeight: "600",
  },
  scoreSection: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    minWidth: "80px",
  },
  finalScore: {
    fontSize: "18px",
    fontWeight: "bold",
    color: "#111827",
  },
  liveScore: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    fontSize: "18px",
    fontWeight: "bold",
    color: "#16a34a",
  },
  minute: {
    fontSize: "12px",
    color: "#16a34a",
    marginTop: "2px",
  },
  time: {
    display: "flex",
    alignItems: "center",
    gap: "4px",
    fontSize: "16px",
    color: "#6b7280",
  },
  venue: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    marginTop: "12px",
    paddingTop: "12px",
    borderTop: "1px solid #f3f4f6",
    fontSize: "14px",
    color: "#6b7280",
  },
  matchActions: {
    display: "flex",
    gap: "8px",
    marginTop: "16px",
  },
  liveActionButton: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    backgroundColor: "#10b981",
    color: "white",
    border: "none",
    padding: "8px 16px",
    borderRadius: "6px",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: "500",
  },
  matchSelector: {
    backgroundColor: "white",
    padding: "20px",
    borderRadius: "12px",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.1)",
    marginBottom: "24px",
  },
  selectorLabel: {
    display: "block",
    fontSize: "14px",
    fontWeight: "600",
    color: "#374151",
    marginBottom: "8px",
  },
  selector: {
    width: "100%",
    padding: "12px",
    border: "1px solid #d1d5db",
    borderRadius: "8px",
    fontSize: "16px",
  },
  matchInfo: {
    backgroundColor: "white",
    padding: "24px",
    borderRadius: "12px",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.1)",
    marginBottom: "24px",
  },
  matchTeams: {
    display: "flex",
    alignItems: "center",
    gap: "20px",
    fontSize: "18px",
    fontWeight: "600",
  },
  matchScore: {
    fontSize: "24px",
    fontWeight: "bold",
    backgroundColor: "#f3f4f6",
    padding: "8px 16px",
    borderRadius: "8px",
  },
  currentTime: {
    fontSize: "16px",
    fontWeight: "bold",
    color: "#16a34a",
  },
  mainContent: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "24px",
  },
  eventForm: {
    backgroundColor: "white",
    padding: "24px",
    borderRadius: "12px",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.1)",
  },
  form: {
    display: "flex",
    flexDirection: "column",
    gap: "20px",
  },
  formRow: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "16px",
  },
  formGroup: {
    display: "flex",
    flexDirection: "column",
  },
  label: {
    fontSize: "14px",
    fontWeight: "600",
    color: "#374151",
    marginBottom: "6px",
  },
  input: {
    padding: "10px",
    border: "1px solid #d1d5db",
    borderRadius: "6px",
    fontSize: "14px",
  },
  addButton: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    backgroundColor: "#16a34a",
    color: "white",
    border: "none",
    padding: "12px 24px",
    borderRadius: "8px",
    fontSize: "16px",
    fontWeight: "600",
    cursor: "pointer",
  },
  eventsList: {
    backgroundColor: "white",
    padding: "24px",
    borderRadius: "12px",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.1)",
  },
  eventsContainer: {
    maxHeight: "500px",
    overflowY: "auto",
  },
  eventItem: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    padding: "12px",
    borderBottom: "1px solid #f3f4f6",
    backgroundColor: "#fafafa",
    borderRadius: "8px",
    marginBottom: "8px",
  },
  eventTime: {
    fontSize: "14px",
    fontWeight: "bold",
    color: "#16a34a",
    minWidth: "40px",
    textAlign: "center",
    backgroundColor: "#dcfce7",
    padding: "4px 8px",
    borderRadius: "4px",
  },
  eventIcon: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    minWidth: "32px",
  },
  eventDetails: {
    flex: 1,
  },
  eventType: {
    fontWeight: "600",
    color: "#111827",
    fontSize: "14px",
  },
  eventPlayer: {
    color: "#6b7280",
    fontSize: "13px",
  },
  eventTeam: {
    color: "#3b82f6",
    fontSize: "12px",
    fontWeight: "500",
  },
  noEvents: {
    textAlign: "center",
    padding: "40px",
    color: "#6b7280",
  },
};
