// ==================== STYLES ====================
export const styles = {
  container: {
    padding: "24px",
    maxWidth: "1200px",
    margin: "0 auto",
  },
  loadingContainer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: "400px",
    fontSize: "16px",
    color: "#6b7280",
  },
  header: {
    marginBottom: "32px",
  },
  title: {
    fontSize: "28px",
    fontWeight: "bold",
    color: "#111827",
    marginBottom: "8px",
  },
  subtitle: {
    fontSize: "16px",
    color: "#6b7280",
  },
  message: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "12px 16px",
    borderRadius: "8px",
    marginBottom: "24px",
    fontSize: "14px",
  },
  form: {
    backgroundColor: "white",
    padding: "32px",
    borderRadius: "12px",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.1)",
  },
  formGroup: {
    marginBottom: "24px",
  },
  formRow: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "20px",
    marginBottom: "24px",
  },
  label: {
    display: "block",
    fontSize: "14px",
    fontWeight: "600",
    color: "#374151",
    marginBottom: "8px",
  },
  input: {
    width: "100%",
    padding: "12px",
    border: "1px solid #d1d5db",
    borderRadius: "8px",
    fontSize: "16px",
  },
  textarea: {
    width: "100%",
    padding: "12px",
    border: "1px solid #d1d5db",
    borderRadius: "8px",
    fontSize: "16px",
    resize: "vertical",
  },
  fileUpload: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "32px",
    border: "2px dashed #d1d5db",
    borderRadius: "8px",
    textAlign: "center",
    cursor: "pointer",
    position: "relative",
  },
  fileInput: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    opacity: 0,
    cursor: "pointer",
  },
  submitButton: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    backgroundColor: "#3b82f6",
    color: "white",
    padding: "12px 24px",
    border: "none",
    borderRadius: "8px",
    fontSize: "16px",
    fontWeight: "600",
    cursor: "pointer",
  },
  metricsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(250px, 1fr))",
    gap: "20px",
    marginBottom: "32px",
  },
  metricCard: {
    display: "flex",
    alignItems: "center",
    backgroundColor: "white",
    padding: "24px",
    borderRadius: "12px",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.1)",
  },
  metricIcon: {
    backgroundColor: "#eff6ff",
    color: "#3b82f6",
    padding: "12px",
    borderRadius: "10px",
    marginRight: "16px",
  },
  metricContent: {},
  metricValue: {
    fontSize: "24px",
    fontWeight: "bold",
    color: "#111827",
  },
  metricLabel: {
    fontSize: "14px",
    color: "#6b7280",
  },
  statsSection: {
    backgroundColor: "white",
    padding: "24px",
    borderRadius: "12px",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.1)",
    marginBottom: "32px",
  },
  sectionTitle: {
    fontSize: "20px",
    fontWeight: "bold",
    marginBottom: "20px",
  },
  statsTable: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  statRow: {
    display: "flex",
    justifyContent: "space-between",
    padding: "12px 0",
    borderBottom: "1px solid #f3f4f6",
  },
  playersSection: {
    backgroundColor: "white",
    padding: "24px",
    borderRadius: "12px",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.1)",
  },
  playersList: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(300px, 1fr))",
    gap: "16px",
  },
  playerCard: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "16px",
    backgroundColor: "#f9fafb",
    borderRadius: "8px",
  },
  playerInfo: {},
  playerName: {
    fontWeight: "600",
    color: "#111827",
  },
  playerPosition: {
    fontSize: "14px",
    color: "#6b7280",
  },
  playerStats: {},
  playerStat: {
    fontSize: "14px",
    color: "#6b7280",
  },
  filters: {
    display: "flex",
    gap: "12px",
    marginBottom: "24px",
  },
  filterButton: {
    padding: "8px 16px",
    border: "1px solid #d1d5db",
    backgroundColor: "white",
    borderRadius: "6px",
    cursor: "pointer",
  },
  activeFilter: {
    backgroundColor: "#3b82f6",
    color: "white",
    borderColor: "#3b82f6",
  },
  matchesList: {
    display: "flex",
    flexDirection: "column",
    gap: "16px",
  },
  matchCard: {
    backgroundColor: "white",
    padding: "20px",
    borderRadius: "12px",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.1)",
  },
  matchHeader: {
    display: "flex",
    justifyContent: "space-between",
    marginBottom: "16px",
  },
  matchDate: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    fontSize: "14px",
    color: "#6b7280",
  },
  matchTime: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    fontSize: "14px",
    color: "#6b7280",
  },
  matchContent: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  teams: {
    display: "flex",
    alignItems: "center",
    gap: "24px",
    flex: 1,
  },
  team: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    minWidth: "120px",
  },
  teamName: {
    fontWeight: "600",
    textAlign: "center",
  },
  homeIndicator: {
    fontSize: "12px",
    color: "#059669",
    backgroundColor: "#d1fae5",
    padding: "2px 6px",
    borderRadius: "4px",
    marginTop: "4px",
  },
  awayIndicator: {
    fontSize: "12px",
    color: "#dc2626",
    backgroundColor: "#fee2e2",
    padding: "2px 6px",
    borderRadius: "4px",
    marginTop: "4px",
  },
  score: {
    fontSize: "18px",
    fontWeight: "bold",
    color: "#111827",
  },
  result: {
    padding: "6px 12px",
    borderRadius: "6px",
    fontSize: "14px",
    fontWeight: "600",
  },
  matchFooter: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    marginTop: "12px",
    paddingTop: "12px",
    borderTop: "1px solid #f3f4f6",
    fontSize: "14px",
    color: "#6b7280",
  },
  emptyState: {
    textAlign: "center",
    padding: "40px",
    color: "#6b7280",
  },
};
