// ==================== STYLES ====================
export const styles = {
  container: {
    padding: "24px",
    maxWidth: "1200px",
    margin: "0 auto",
  },
  loadingContainer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: "400px",
    fontSize: "16px",
    color: "#6b7280",
  },
  header: {
    marginBottom: "32px",
  },
  title: {
    fontSize: "28px",
    fontWeight: "bold",
    color: "#111827",
    marginBottom: "8px",
  },
  subtitle: {
    fontSize: "16px",
    color: "#6b7280",
  },
  message: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "12px 16px",
    borderRadius: "8px",
    marginBottom: "24px",
    fontSize: "14px",
  },
  metricsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
    gap: "20px",
    marginBottom: "32px",
  },
  metricCard: {
    display: "flex",
    alignItems: "center",
    backgroundColor: "white",
    padding: "24px",
    borderRadius: "12px",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.1)",
  },
  metricIcon: {
    backgroundColor: "#eff6ff",
    color: "#3b82f6",
    padding: "12px",
    borderRadius: "10px",
    marginRight: "16px",
  },
  metricContent: {
    flex: 1,
  },
  metricValue: {
    fontSize: "24px",
    fontWeight: "bold",
    color: "#111827",
  },
  metricLabel: {
    fontSize: "14px",
    color: "#6b7280",
  },
  metricSubtext: {
    fontSize: "12px",
    color: "#9ca3af",
    marginTop: "2px",
  },
  dashboardGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(400px, 1fr))",
    gap: "24px",
  },
  section: {
    backgroundColor: "white",
    padding: "24px",
    borderRadius: "12px",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.1)",
  },
  sectionHeader: {
    marginBottom: "20px",
  },
  sectionTitle: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontSize: "18px",
    fontWeight: "bold",
    color: "#111827",
  },
  leaderboard: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  leaderboardItem: {
    display: "flex",
    alignItems: "center",
    gap: "16px",
    padding: "12px",
    backgroundColor: "#f9fafb",
    borderRadius: "8px",
  },
  position: {
    fontSize: "16px",
    fontWeight: "bold",
    color: "#374151",
    minWidth: "30px",
  },
  teamInfo: {
    flex: 1,
  },
  teamName: {
    fontWeight: "600",
    color: "#111827",
  },
  teamStats: {
    fontSize: "14px",
    color: "#6b7280",
  },
  teamPoints: {
    textAlign: "right",
  },
  points: {
    fontSize: "16px",
    fontWeight: "bold",
    color: "#059669",
  },
  goalDiff: {
    fontSize: "12px",
    color: "#6b7280",
  },
  activitiesList: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  activityItem: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    padding: "12px",
    backgroundColor: "#f9fafb",
    borderRadius: "8px",
  },
  activityIcon: {
    backgroundColor: "#eff6ff",
    color: "#3b82f6",
    padding: "8px",
    borderRadius: "6px",
  },
  activityContent: {
    flex: 1,
  },
  activityMessage: {
    fontSize: "14px",
    color: "#111827",
  },
  activityTime: {
    fontSize: "12px",
    color: "#6b7280",
  },
  activityStatus: {},
  statusLive: {
    backgroundColor: "#dcfce7",
    color: "#16a34a",
    padding: "2px 6px",
    borderRadius: "4px",
    fontSize: "12px",
    fontWeight: "600",
  },
  statusNew: {
    backgroundColor: "#dbeafe",
    color: "#3b82f6",
    padding: "2px 6px",
    borderRadius: "4px",
    fontSize: "12px",
    fontWeight: "600",
  },
  noActivities: {
    textAlign: "center",
    padding: "20px",
    color: "#6b7280",
  },
  roleStats: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  roleItem: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  roleLabel: {
    minWidth: "80px",
    fontSize: "14px",
    fontWeight: "500",
  },
  roleCount: {
    minWidth: "30px",
    fontSize: "14px",
    fontWeight: "bold",
  },
  roleBar: {
    flex: 1,
    height: "8px",
    backgroundColor: "#f3f4f6",
    borderRadius: "4px",
    overflow: "hidden",
  },
  roleBarFill: {
    height: "100%",
    transition: "width 0.3s ease",
  },
  alertsList: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  alertItem: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "8px 12px",
    backgroundColor: "#fffbeb",
    borderRadius: "6px",
    fontSize: "14px",
    color: "#92400e",
  },
  noAlerts: {
    textAlign: "center",
    padding: "20px",
    color: "#6b7280",
  },
  filtersSection: {
    display: "flex",
    alignItems: "center",
    gap: "20px",
    backgroundColor: "white",
    padding: "20px",
    borderRadius: "12px",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.1)",
    marginBottom: "24px",
  },
  filterGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  filterLabel: {
    fontSize: "14px",
    fontWeight: "600",
    color: "#374151",
  },
  select: {
    padding: "8px 12px",
    border: "1px solid #d1d5db",
    borderRadius: "6px",
    fontSize: "14px",
  },
  exportButton: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    backgroundColor: "#3b82f6",
    color: "white",
    border: "none",
    padding: "10px 16px",
    borderRadius: "6px",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: "500",
  },
  reportContent: {
    backgroundColor: "white",
    padding: "24px",
    borderRadius: "12px",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.1)",
  },
  reportGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))",
    gap: "24px",
  },
  reportCard: {
    backgroundColor: "#f9fafb",
    padding: "20px",
    borderRadius: "8px",
    border: "1px solid #e5e7eb",
  },
  cardTitle: {
    fontSize: "16px",
    fontWeight: "bold",
    color: "#111827",
    marginBottom: "16px",
  },
  summaryGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, 1fr)",
    gap: "16px",
  },
  summaryItem: {
    textAlign: "center",
    padding: "12px",
    backgroundColor: "white",
    borderRadius: "6px",
  },
  summaryValue: {
    fontSize: "20px",
    fontWeight: "bold",
    color: "#111827",
  },
  summaryLabel: {
    fontSize: "12px",
    color: "#6b7280",
    marginTop: "4px",
  },
  chartContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  barItem: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  barLabel: {
    minWidth: "60px",
    fontSize: "14px",
    fontWeight: "500",
  },
  barContainer: {
    flex: 1,
    height: "20px",
    backgroundColor: "#f3f4f6",
    borderRadius: "10px",
    overflow: "hidden",
  },
  bar: {
    height: "100%",
    transition: "width 0.3s ease",
  },
  barValue: {
    minWidth: "30px",
    fontSize: "14px",
    fontWeight: "bold",
    textAlign: "right",
  },
  statusList: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  statusItem: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "8px 12px",
    backgroundColor: "white",
    borderRadius: "4px",
  },
  statusLabel: {
    fontSize: "14px",
    color: "#374151",
  },
  statusCount: {
    fontSize: "14px",
    fontWeight: "bold",
    color: "#111827",
  },
  teamsList: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  teamItem: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "6px 0",
    borderBottom: "1px solid #e5e7eb",
  },
  teamMatches: {
    fontSize: "12px",
    color: "#6b7280",
  },
  statsList: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  statItem: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "12px 0",
    borderBottom: "1px solid #e5e7eb",
  },
  statValue: {
    fontSize: "16px",
    fontWeight: "bold",
    color: "#059669",
  },
  monthlyChart: {
    display: "flex",
    alignItems: "end",
    gap: "8px",
    height: "150px",
    padding: "10px 0",
  },
  monthItem: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    flex: 1,
    height: "100%",
  },
  monthLabel: {
    fontSize: "10px",
    color: "#6b7280",
    marginBottom: "8px",
  },
  monthBar: {
    width: "20px",
    flex: 1,
    backgroundColor: "#f3f4f6",
    borderRadius: "2px",
    overflow: "hidden",
    display: "flex",
    alignItems: "end",
  },
  monthBarFill: {
    width: "100%",
    backgroundColor: "#3b82f6",
    transition: "height 0.3s ease",
  },
  monthValue: {
    fontSize: "10px",
    color: "#374151",
    marginTop: "4px",
  },
  topMatches: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  matchRow: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    padding: "8px",
    backgroundColor: "white",
    borderRadius: "4px",
  },
  matchRank: {
    minWidth: "30px",
    fontSize: "14px",
    fontWeight: "bold",
    color: "#6b7280",
  },
  matchDetails: {
    flex: 1,
  },
  matchTeams: {
    fontSize: "14px",
    fontWeight: "500",
  },
  matchScore: {
    fontSize: "12px",
    color: "#6b7280",
  },
  matchGoals: {
    fontSize: "14px",
    fontWeight: "bold",
    color: "#059669",
  },
  teamsTable: {
    display: "flex",
    flexDirection: "column",
  },
  tableHeader: {
    display: "grid",
    gridTemplateColumns: "2fr 1fr 1fr 1fr",
    gap: "12px",
    padding: "12px",
    backgroundColor: "#f3f4f6",
    borderRadius: "4px",
    fontSize: "12px",
    fontWeight: "bold",
    color: "#6b7280",
    textTransform: "uppercase",
  },
  tableRow: {
    display: "grid",
    gridTemplateColumns: "2fr 1fr 1fr 1fr",
    gap: "12px",
    padding: "12px",
    borderBottom: "1px solid #e5e7eb",
    fontSize: "14px",
  },
  hasManager: {
    color: "#16a34a",
    fontWeight: "bold",
  },
  noManager: {
    color: "#dc2626",
    fontWeight: "bold",
  },
  settingsContainer: {
    backgroundColor: "white",
    borderRadius: "12px",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.1)",
    overflow: "hidden",
  },
  tabsContainer: {
    display: "flex",
    borderBottom: "1px solid #e5e7eb",
  },
  tab: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "16px 24px",
    backgroundColor: "transparent",
    border: "none",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: "500",
    color: "#6b7280",
    borderBottom: "2px solid transparent",
    transition: "all 0.2s ease",
  },
  activeTab: {
    color: "#3b82f6",
    borderBottomColor: "#3b82f6",
    backgroundColor: "#f8fafc",
  },
  tabContent: {
    padding: "32px",
  },
  settingsSection: {
    display: "flex",
    flexDirection: "column",
    gap: "24px",
  },
  settingGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  settingRow: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "20px",
  },
  settingLabel: {
    fontSize: "14px",
    fontWeight: "600",
    color: "#374151",
  },
  settingInput: {
    padding: "10px 12px",
    border: "1px solid #d1d5db",
    borderRadius: "6px",
    fontSize: "14px",
  },
  settingTextarea: {
    padding: "10px 12px",
    border: "1px solid #d1d5db",
    borderRadius: "6px",
    fontSize: "14px",
    resize: "vertical",
  },
  settingSelect: {
    padding: "10px 12px",
    border: "1px solid #d1d5db",
    borderRadius: "6px",
    fontSize: "14px",
    backgroundColor: "white",
  },
  checkboxGroup: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  checkbox: {
    width: "16px",
    height: "16px",
  },
  checkboxLabel: {
    fontSize: "14px",
    fontWeight: "500",
    color: "#374151",
    cursor: "pointer",
  },
  saveButton: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    backgroundColor: "#3b82f6",
    color: "white",
    border: "none",
    padding: "12px 24px",
    borderRadius: "8px",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: "600",
    alignSelf: "flex-start",
  },
  notificationSettings: {
    display: "flex",
    flexDirection: "column",
    gap: "16px",
  },
  dangerZone: {
    border: "1px solid #fecaca",
    borderRadius: "8px",
    padding: "20px",
    backgroundColor: "#fef2f2",
  },
  dangerTitle: {
    fontSize: "16px",
    fontWeight: "bold",
    color: "#dc2626",
    marginBottom: "16px",
  },
  dangerCheckboxLabel: {
    fontSize: "14px",
    fontWeight: "500",
    color: "#dc2626",
    cursor: "pointer",
  },
  dangerDescription: {
    fontSize: "12px",
    color: "#6b7280",
    marginTop: "4px",
    fontStyle: "italic",
  },
};
